### PR TITLE
Removed deprecated sensor param

### PR DESCRIPTION
**Pull request by scriptist**
This entirely removes the sensor parameter, which has been deprecated by Google. See discussion in PR #32.

### CODE REVIEW

**Comment by davidkudera** [comment]
Thank you so much sir :beers:

**Comment by scriptist** [comment]
No worries - thank YOU for maintaining this excellent repo :)

**Comment by scriptist** [comment]
Any chance 3.2.0 could be released soon? It'd be good to remove Google's deprecation warning from master :)

**Comment by davidkudera** [comment]
@scriptist right [now](https://github.com/Carrooi/Js-GoogleMapsLoader/tree/3.2.0) :wink:

**Comment by scriptist** [comment]
:+1:

Just realised I didn't remove the 'sensor' bit from the readme. Oops.

**Comment by davidkudera** [comment]
@scriptist ouch.... :laughing: 

I released also 3.2.1

**Comment by scriptist** [comment]
:+1: :+1: Even better :D

**Pull request merged**
