### PR TITLE
Region parameter support / optional sensor parameter

### PR DESCRIPTION
**Pull request by huyby**
Adding a region parameter: https://developers.google.com/maps/documentation/javascript/basics#Region
Also made the "sensor" parameter optional as it's no longer required: https://developers.google.com/maps/documentation/javascript/error-messages (SensorNotRequired)

### CODE REVIEW

**Comment by davidkudera** [comment]
Thank you :+1: 

One last thing, can you please squash all commits together?

**Comment by huyby** [comment]
I hope it's ok now, I used rebase to squash the 4 commits into one.
Never 'squashed' commits before, interesting :-)

**Comment by dincho** [comment]
> I hope it's ok now, I used rebase to squash the 4 commits into one.
> Never 'squashed' commits before, interesting :-)

You actually didn't :) Can you try again?

**Comment by davidkudera** [comment]
Closing in favor of #36 
Thanks anyway :+1:

**Comment by dincho** [comment]
@davidkudera what about the sensor param?

**Comment by davidkudera** [comment]
@dincho done in #34 :wink:

**Comment by dincho** [comment]
Great, thank I missed that.

**Pull request closed without merging**
