### PR TITLE
fix some issues and bump version

### PR DESCRIPTION
**Pull request by thecotne**

### CODE REVIEW

**Comment by sakren** [comment]
Thank you :wink: 

I'm just not sure about the new version... Especially when I'm planning to rename npm and bower packages to `google-maps-loader`

So please, may I ask you to remove that commit for now?

**Comment by thecotne** [comment]
done

**Comment by thecotne** [comment]
but now you have feature which is in docs and implemented in code but not supported with latest release

**Comment by sakren** [comment]
#20

**Pull request merged**
